name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        :warning: **Issues will be marked as invalid if they do not come with profiling data and analysis to support the claim.**
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        - If [disabling uBlock Origin](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button) (uBO) makes the issue go away, then it is probably a filter issue.
        - However, if the issue is still present *after* disabling uBO, then the issue is unrelated to a filter.
        - See what the [logger reports](https://github.com/gorhill/uBlock/wiki/The-logger) when you reproduce the issue. This will help you determine whether this is a filter issue.
        - To rule out invalid issues, confirm each one of the checkboxes:
      options:
        - label: I am not using any other content blockers alongside uBO (Privacy Badger, AdGuard, Ghostery, Adblock Plus, etc.)
          required: true
        - label: I verified that this is not a [known filter issue](https://github.com/yokoffing/filterlists/issues)
          required: true
        - label: This is not a [support issue or a question](https://old.reddit.com/r/uBlockOrigin/)
          required: true
        - label: I performed a [cursory search of the uBO issue tracker](https://github.com/uBlockOrigin/uBlock-issues/issues?q=is%3Aissue) to avoid opening a duplicate issue
          required: true
        - label: The issue is not present after wholly disabling uBO in the browser
          required: true
    
  - type: checkboxes
    attributes:
      label: I tried to reproduce the issue when...
      options:
        - label: uBO is the only extension
          required: true
        - label: uBO with default lists/settings
          required: true
        - label: using a new, unmodified browser profile
          required: true

  - type: textarea
    attributes:
      label: Specific URL(s) where the issue occurs
      description: A specific URL is MANDATORY for issue happening on a web page, even if it happens "everywhere"
      render: 
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Description
      description: Description of the bug or feature
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: How do we reproduce the issue?
      placeholder: |
        1. [First Step]
        2. [Second Step]
        3. [and so on...]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Logger Output
      description: Open [the logger](https://github.com/gorhill/uBlock/wiki/The-logger)
      placeholder: |
        - Open [the logger](https://github.com/gorhill/uBlock/wiki/The-logger)
        - Refresh the issue page
        - [Export](https://github.com/gorhill/uBlock/wiki/The-logger#export-dialog) the output by clicking the clipboard icon
        - Select `Table` and `Markdown`, then `Copy to clipboard`
        - Paste output below
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you wanted to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual behavior
      description: What happened instead
    validations:
      required: true

  - type: input
    attributes:
      label: uBlock Origin version
    validations:
      required: true

  - type: input
    attributes:
      label: Browser name and version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System and version
    validations:
      required: true
